#!/usr/bin/env python3
"""Build the checked-in Rust catalog and typed shader bundle.

Inputs are a source directory containing metadata.json, bundle-lock.json, and
either extracted effects.json or a cache-compatible effects/ tree.  Existing
hashes are an immutable contract: there is intentionally no update-lock mode.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.transpiler.typed_ir import emit_typed_ir


EXPECTED_EXCLUSIONS = [
    "render/meshLoader",
    "render/meshRender",
    "synth/roll",
    "synth/scope",
    "synth/spectrum",
]
PARAM_CONTRACT = Path(__file__).with_name("upstream-param-contract.json")
PARAM_OVERRIDE_FIELDS = frozenset({"min", "max"})
REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPOSITORY_ROOT / "src/generated"
EFFECTS_DOCUMENT = REPOSITORY_ROOT / "docs/EFFECTS.md"


def _read_json(path: Path) -> dict:
    with path.open(encoding="utf-8") as stream:
        return json.load(stream)


def _write_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _effects_markdown(catalog: dict) -> str:
    effects = catalog["effects"]
    namespace_counts: dict[str, int] = {}
    by_namespace: dict[str, list[str]] = {}
    choices: list[tuple[str, str, str, object]] = []
    for effect_id, effect in sorted(effects.items()):
        namespace = effect["namespace"]
        namespace_counts[namespace] = namespace_counts.get(namespace, 0) + 1
        by_namespace.setdefault(namespace, []).append(effect_id)
        for parameter, spec in sorted(effect.get("params", {}).items()):
            if spec.get("define") is None or not isinstance(spec.get("choices"), dict):
                continue
            for label, value in sorted(spec["choices"].items()):
                if value is not None:
                    choices.append((effect_id, parameter, label, value))

    lines = [
        "# Effect reference",
        "",
        "<!-- Generated by scripts/generate_bundle.py; do not edit by hand. -->",
        "",
        f"This build contains **{len(effects)}** CPU effects and "
        f"**{len(choices)}** non-null compile-time choices.",
        "",
        "## Namespace counts",
        "",
        "| Namespace | Effects |",
        "| --- | ---: |",
    ]
    lines.extend(
        f"| `{namespace}` | {count} |"
        for namespace, count in sorted(namespace_counts.items())
    )
    lines.extend(
        [
            "",
            "## Upstream exclusions",
            "",
            "These five effects require media/runtime interfaces that are not part of this "
            "standalone CPU port:",
            "",
        ]
    )
    lines.extend(f"- `{effect_id}`" for effect_id in catalog["excludedEffects"])
    lines.extend(["", "## Effect IDs", ""])
    for namespace, effect_ids in sorted(by_namespace.items()):
        lines.extend([f"### {namespace} ({len(effect_ids)})", ""])
        lines.extend(f"- `{effect_id}`" for effect_id in effect_ids)
        lines.append("")

    lines.extend(
        [
            "## Compile-time choices",
            "",
            "Each row is a non-null named value for a parameter backed by a shader define.",
            "",
            "| Effect | Parameter | Choice | Value |",
            "| --- | --- | --- | ---: |",
        ]
    )
    lines.extend(
        f"| `{effect_id}` | `{parameter}` | `{label}` | `{json.dumps(value)}` |"
        for effect_id, parameter, label, value in choices
    )
    lines.extend(
        [
            "",
            "## Cost and state notes",
            "",
            "- Iterated effects have a catalog default of 60 iterations. Runtime cost scales "
            "with canvas size and iteration count.",
            "- Volume storage and work scale cubically with `volumeSize`; choose small values "
            "when exploring effects.",
            "- Particle filters require an owning `pointsEmit`/state/`pointsRender` chain for "
            "meaningful standalone execution.",
            "- Loop markers must be paired around the chain they repeat.",
            "- External-texture effects require the named image input to be bound.",
            "",
        ]
    )
    return "\n".join(lines)


def write_effects_document(catalog_path: Path, document_path: Path) -> None:
    document_path.parent.mkdir(parents=True, exist_ok=True)
    document_path.write_text(_effects_markdown(_read_json(catalog_path)), encoding="utf-8")


def check_effects_document(catalog: dict, document_path: Path = EFFECTS_DOCUMENT) -> None:
    expected = _effects_markdown(catalog)
    if not document_path.exists() or document_path.read_text(encoding="utf-8") != expected:
        raise RuntimeError(f"generated effect reference is stale: {document_path}")


def _load_effects(source: Path) -> dict:
    aggregate = source / "effects.json"
    if aggregate.exists():
        return _read_json(aggregate)
    effects_root = source / "effects"
    if not effects_root.is_dir():
        raise RuntimeError(f"source has neither effects.json nor effects/: {source}")
    effects = {}
    for path in sorted(effects_root.rglob("*.json")):
        if path.name == "manifest.json":
            continue
        effect = _read_json(path)
        effect_id = effect.get("id") or path.relative_to(effects_root).with_suffix("").as_posix()
        effects[effect_id] = effect
    return effects


def _runtime_defines(parameters: dict) -> dict[str, str]:
    return {
        spec["define"]: "float" if spec.get("type") == "float" else "int"
        for spec in parameters.values()
        if isinstance(spec, dict) and spec.get("define")
    }


def _pass_outputs(render_pass: dict) -> list[str]:
    names = list(render_pass.get("outputs", {}).keys()) or ["fragColor"]
    if "color" in names and "fragColor" not in names:
        names[names.index("color")] = "fragColor"
    return names


def _validate_inventory(metadata: dict, effects: dict, lock: dict) -> tuple[dict[str, dict], dict[str, str]]:
    catalog_effects = metadata.get("effects")
    hashes = lock.get("hashes")
    if not isinstance(catalog_effects, dict) or not isinstance(hashes, dict):
        raise RuntimeError("metadata/lock schemas are missing effects or hashes")
    pass_keys = {
        render_pass["key"]
        for definition in catalog_effects.values()
        for render_pass in definition.get("passes", [])
        if render_pass.get("key") is not None
    }
    source_keys = {
        f"{effect_id}:{program}"
        for effect_id, effect in effects.items()
        for program in effect.get("programs", {})
    }
    if pass_keys != set(hashes) or pass_keys != source_keys:
        raise RuntimeError(
            "bundle inventory mismatch: "
            f"metadata={len(pass_keys)} lock={len(hashes)} source={len(source_keys)}"
        )
    if set(catalog_effects) != set(effects):
        raise RuntimeError(
            f"effect inventory mismatch: metadata={len(catalog_effects)} source={len(effects)}"
        )
    return catalog_effects, hashes


def _apply_param_contract(source: Path, catalog_effects: dict) -> tuple[dict, dict]:
    contract_path = source / "param-contract.json"
    if not contract_path.exists():
        contract_path = PARAM_CONTRACT
    contract = _read_json(contract_path)
    records = contract.get("effects")
    if not isinstance(records, dict) or set(records) != set(catalog_effects):
        raise RuntimeError(
            "parameter contract effect inventory differs from canonical metadata: "
            f"contract={len(records) if isinstance(records, dict) else 'invalid'} "
            f"metadata={len(catalog_effects)}"
        )
    enriched = copy.deepcopy(catalog_effects)
    for effect_id, definition in enriched.items():
        params = definition.get("params", {})
        record = records[effect_id]
        source_names = record.get("paramNames")
        aliases = record.get("paramAliases")
        overrides = record.get("paramOverrides", {})
        if not isinstance(source_names, list) or not all(isinstance(name, str) for name in source_names):
            raise RuntimeError(f"parameter contract for {effect_id} has invalid paramNames")
        names = [name for name in source_names if name in params]
        if len(names) != len(set(names)) or set(names) != set(params):
            raise RuntimeError(f"parameter contract for {effect_id} does not exactly order canonical params")
        if not isinstance(aliases, dict) or not all(
            isinstance(alias, str) and isinstance(target, str)
            for alias, target in aliases.items()
        ):
            raise RuntimeError(f"parameter contract for {effect_id} has invalid paramAliases")
        if not isinstance(overrides, dict):
            raise RuntimeError(f"parameter contract for {effect_id} has invalid paramOverrides")
        for alias, target in aliases.items():
            if alias in params:
                raise RuntimeError(
                    f"parameter alias {effect_id}.{alias} collides with canonical parameter"
                )
            if target not in params:
                raise RuntimeError(
                    f"parameter alias {effect_id}.{alias} targets unknown parameter {target}"
                )
        for name, values in overrides.items():
            if name not in params or not isinstance(values, dict):
                raise RuntimeError(
                    f"parameter override {effect_id}.{name} targets unknown parameter"
                )
            if not values or not set(values).issubset(PARAM_OVERRIDE_FIELDS) or not all(
                isinstance(value, (int, float)) and not isinstance(value, bool)
                for value in values.values()
            ):
                raise RuntimeError(f"parameter override {effect_id}.{name} is invalid")
            params[name].update(values)
        definition["paramNames"] = names
        definition["paramAliases"] = aliases
    return enriched, contract


def _build(source: Path) -> tuple[dict, dict, dict]:
    metadata = _read_json(source / "metadata.json")
    lock = _read_json(source / "bundle-lock.json")
    effects = _load_effects(source)
    catalog_effects, hashes = _validate_inventory(metadata, effects, lock)
    catalog_effects, param_contract = _apply_param_contract(source, catalog_effects)
    programs = {}
    for effect_id in sorted(catalog_effects):
        definition = catalog_effects[effect_id]
        source_effect = effects[effect_id]
        defines = _runtime_defines(definition.get("params", {}))
        passes = {render_pass.get("key"): render_pass for render_pass in definition.get("passes", [])}
        for program_name, shader_source in sorted(source_effect.get("programs", {}).items()):
            key = f"{effect_id}:{program_name}"
            digest = hashlib.sha256(shader_source.strip().encode("utf-8")).hexdigest()
            if digest != hashes[key]:
                raise RuntimeError(
                    f"shader drift for {key}: expected {hashes[key]}, received {digest}"
                )
            render_pass = passes[key]
            programs[key] = {
                "effectId": effect_id,
                "program": program_name,
                "sourceSha256": digest,
                "ir": emit_typed_ir(
                    shader_source,
                    outputs=_pass_outputs(render_pass),
                    varyings=[],
                    runtime_defines=defines,
                ),
            }
    provenance = dict(metadata.get("provenance", {}))
    provenance["lockSource"] = lock.get("source")
    provenance["lockVersion"] = lock.get("version")
    provenance["paramContractSource"] = param_contract.get("source")
    provenance["paramContractRevision"] = param_contract.get("revision")
    catalog = {
        "provenance": provenance,
        "excludedEffects": EXPECTED_EXCLUSIONS,
        "effects": catalog_effects,
    }
    shaders = {"provenance": provenance, "programs": programs}
    generated_lock = {
        "source": lock.get("source"),
        "version": lock.get("version"),
        "hashes": hashes,
    }
    return catalog, shaders, generated_lock


def generate_bundle(source: os.PathLike[str] | str, output: os.PathLike[str] | str) -> None:
    source_path = Path(source).resolve()
    output_path = Path(output).resolve()
    preserved = output_path / "mod.rs"
    preserved_bytes = preserved.read_bytes() if preserved.exists() else None
    catalog, shaders, lock = _build(source_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    staged = Path(tempfile.mkdtemp(prefix=f".{output_path.name}.build-", dir=output_path.parent))
    backup = None
    try:
        _write_json(staged / "catalog.json", catalog)
        _write_json(staged / "shaders.json", shaders)
        _write_json(staged / "bundle-lock.json", lock)
        if preserved_bytes is not None:
            (staged / "mod.rs").write_bytes(preserved_bytes)
        if output_path.exists():
            backup = Path(tempfile.mkdtemp(prefix=f".{output_path.name}.backup-", dir=output_path.parent))
            backup.rmdir()
            os.replace(output_path, backup)
        os.replace(staged, output_path)
        staged = None
        if backup is not None:
            shutil.rmtree(backup)
    except BaseException:
        if backup is not None and not output_path.exists():
            os.replace(backup, output_path)
        raise
    finally:
        if staged is not None:
            shutil.rmtree(staged, ignore_errors=True)


def _expected_param_contract_provenance(contract_path: Path) -> dict[str, str]:
    contract = _read_json(contract_path)
    expected = {
        "paramContractSource": contract.get("source"),
        "paramContractRevision": contract.get("revision"),
    }
    if not all(isinstance(value, str) and value for value in expected.values()):
        raise RuntimeError(f"parameter contract provenance is invalid: {contract_path}")
    return expected


def sync_param_contract_provenance(
    output: os.PathLike[str] | str,
    contract_path: os.PathLike[str] | str = PARAM_CONTRACT,
) -> None:
    output_path = Path(output).resolve()
    expected = _expected_param_contract_provenance(Path(contract_path).resolve())
    staged_root = Path(tempfile.mkdtemp(prefix=f".{output_path.name}.provenance-", dir=output_path.parent))
    staged_output = staged_root / output_path.name
    backup = None
    try:
        shutil.copytree(output_path, staged_output)
        for name in ("catalog.json", "shaders.json"):
            path = staged_output / name
            value = _read_json(path)
            provenance = value.get("provenance")
            if not isinstance(provenance, dict):
                raise RuntimeError(f"generated artifact has no provenance object: {path}")
            provenance.update(expected)
            _write_json(path, value)
        check_generated(staged_output, contract_path, check_document=False)
        backup = Path(tempfile.mkdtemp(prefix=f".{output_path.name}.backup-", dir=output_path.parent))
        backup.rmdir()
        os.replace(output_path, backup)
        os.replace(staged_output, output_path)
        obsolete = backup
        backup = None
        try:
            shutil.rmtree(obsolete)
        except OSError:
            pass
    except BaseException:
        if backup is not None and not output_path.exists():
            os.replace(backup, output_path)
        raise
    finally:
        shutil.rmtree(staged_root, ignore_errors=True)


def check_generated(
    output: os.PathLike[str] | str,
    contract_path: os.PathLike[str] | str = PARAM_CONTRACT,
    *,
    check_document: bool = True,
) -> None:
    output_path = Path(output).resolve()
    catalog_path = output_path / "catalog.json"
    contract_path = Path(contract_path).resolve()
    contract = _read_json(contract_path)
    catalog = _read_json(catalog_path)
    for path in (catalog_path, output_path / "shaders.json", output_path / "bundle-lock.json"):
        value = _read_json(path)
        canonical = json.dumps(value, indent=2, sort_keys=True) + "\n"
        if path.read_text(encoding="utf-8") != canonical:
            raise RuntimeError(f"generated artifact is not canonical: {path}")
    expected_provenance = _expected_param_contract_provenance(contract_path)
    for name in ("catalog.json", "shaders.json"):
        provenance = _read_json(output_path / name).get("provenance", {})
        for field, expected in expected_provenance.items():
            if provenance.get(field) != expected:
                raise RuntimeError(
                    f"generated {field} drift in {name}: "
                    f"expected {expected!r}, received {provenance.get(field)!r}"
                )
    records = contract["effects"]
    if set(catalog.get("effects", {})) != set(records):
        raise RuntimeError("generated catalog differs from parameter contract inventory")
    for effect_id, record in records.items():
        effect = catalog["effects"][effect_id]
        compatible_names = [name for name in record["paramNames"] if name in effect.get("params", {})]
        if effect.get("paramNames") != compatible_names:
            raise RuntimeError(f"generated paramNames drift for {effect_id}")
        if effect.get("paramAliases") != record["paramAliases"]:
            raise RuntimeError(f"generated paramAliases drift for {effect_id}")
        for name, values in record.get("paramOverrides", {}).items():
            for field, value in values.items():
                if effect["params"][name].get(field) != value:
                    raise RuntimeError(
                        f"generated parameter override drift for {effect_id}.{name}.{field}"
                    )
    if check_document:
        check_effects_document(catalog)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--sync-param-contract-provenance",
        action="store_true",
        help="refresh only generated parameter-contract provenance",
    )
    parser.add_argument(
        "--write-effects-doc",
        action="store_true",
        help="write docs/EFFECTS.md from the checked-in generated catalog",
    )
    args = parser.parse_args(argv)
    try:
        exclusive_modes = sum((args.check, args.write_effects_doc, args.sync_param_contract_provenance))
        if exclusive_modes > 1 or (args.source is not None and args.sync_param_contract_provenance):
            parser.error(
                "--check, --write-effects-doc, and --sync-param-contract-provenance "
                "are mutually exclusive"
            )
        if args.write_effects_doc:
            if args.source is not None:
                parser.error("--write-effects-doc cannot be combined with --source")
            write_effects_document(args.out / "catalog.json", EFFECTS_DOCUMENT)
        elif args.sync_param_contract_provenance:
            sync_param_contract_provenance(args.out)
        elif args.check and args.source is None:
            check_generated(args.out)
        elif args.source is not None:
            if args.check:
                with tempfile.TemporaryDirectory(prefix="noisemaker-rust-check-") as temp:
                    generated = Path(temp) / "generated"
                    generate_bundle(args.source, generated)
                    for name in ("catalog.json", "shaders.json", "bundle-lock.json"):
                        if (generated / name).read_bytes() != (args.out / name).read_bytes():
                            raise RuntimeError(f"generated artifact drift: {name}")
            else:
                generate_bundle(args.source, args.out)
                if args.out.resolve() == DEFAULT_OUTPUT.resolve():
                    write_effects_document(args.out / "catalog.json", EFFECTS_DOCUMENT)
        else:
            parser.error("--source is required unless --check is used")
    except Exception as error:
        print(f"bundle generation failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
